language: php
php:
  - 5.4
  - 5.3
  - 5.2

before_script:
  - composer install --dev
  - cp tests/phpunit.xml.travis tests/phpunit.xml

script: ./vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-text
